config/routes.rb
Rails.application.routes.draw do
  resources :books
  root 'books#index'
  resources :searches
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	validates :name, presence: true
	validates :category, presence: true
	validates :price, presence: true
	validates :isbn, presence: true
	def self.search(search)
		if search
			where(['name LIKE ?', "%#{search}%"])
		else
			all
		end
	end
end

app/models/search.rb
class Search < ApplicationRecord

	def search_books

		books = Book.all

		books = books.where(["name LIKE ?", "%#{keywords}%"]) if keywords.present?
		books = books.where(["category LIKE ?",category]) if category.present?
		books = books.where(["price >= ?", min_price]) if min_price.present?
		books = books.where(["price <= ?", max_price]) if max_price.present?
		books = books.where(["isbn LIKE ?", isbn]) if isbn.present?

		return books

	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.search(params[:search])
    @book = Book.new
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
    
        format.js
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end

    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
      format.js
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :category, :price, :isbn)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController

	def new
		@search = Search.new
		@categories = Book.pluck(:category).uniq
	end	

	def create 
		@search = Search.create(search_params)
		redirect_to @search
	end

	def show
		@search = Search.find(params[:id])
	end

	private

	def search_params
		params.require(:search).permit(:keywords, :category, :min_price, :max_price, :isbn)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/books/_book.html.erb

	<div class='col-md-3 text-center box blog-main' id="book_id_<%= book.id %>" >
  	<div class="card" style="width: 270px; margin-bottom: 20px;" >
			  <div class="card-body text-white bg-danger mb-3" >
			    <h4 class="card-title "><%= book.name %></h4>

			  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><b>Category: </b><%= book.category %></li>
    <li class="list-group-item"><b>Price: </b><%= book.price %></li>
    <li class="list-group-item"><b>ISBN: </b><%= book.isbn %></li>
  </ul>
		  <div class="card-body" >
		  	<div class="btn-group" role="group" aria-label="Basic example">
		    <%= link_to 'Show', book, class: 'card-link btn btn-primary',style: "color: black; background-color: white;" %>
		  	<%= link_to 'Edit', edit_book_path(book), class: 'card-link btn btn-info',style: "color: black; background-color: white;" %>
		    <%= link_to 'Destroy', book, method: :delete, remote: true, class: 'card-link btn btn-danger',style: "color: black; background-color: white;" %>
		</div>
		  </div>
	</div>
</div>

app/views/books/_form.html.erb
<div id ="new">
  <%= form_for(@book, remote: true) do |form| %>
    <% if @book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

        <ul>
        <% @book.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, id: :book_name, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :category %>
      <%= form.text_field :category, id: :book_category, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :price %>
      <%= form.text_field :price, id: :book_price, class: 'form-control' %>
    </div>

    <div class="field">
      <%= form.label :isbn %>
      <%= form.number_field :isbn, id: :book_isbn, class: 'form-control' %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

app/views/books/create.js.erb

$('#exampleModal').modal('hide');
$('.erase').val('');

$('#bookinfo').append('<%= j render @book  %>');
$('.alert').html("<p class='alert alert-success'>Book created</p>")

app/views/books/destroy.js.erb
$('#book_<%= @book.id %>').remove();
$('.alert').html("<p class='alert alert-danger'>Book Removed</p>")

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<!-- Button trigger modal -->
<div class="text-center">
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  New Book
</button>
</div>
<br>
<br>
<div class="row" id="bookinfo">


        <%= render @books %>

</div>

    <%= form_for(@book, remote: true) do |form| %>
<!-- Modal -->
<div id ="new">
<div class="modal fade" data-backdrop="" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Form</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      

              <div class="modal-body">
                
              <% if @book.errors.any? %>
                <div id="error_explanation">
                  <h2><%= pluralize(@book.errors.count, "error") %> prohibited this book from being saved:</h2>

                  <ul>
                  <% @book.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                  </ul>
                </div>
              <% end %>

              <div class="field">
                <%= form.label :name %>
                <%= form.text_field :name, id: :book_name, class: 'form-control erase' %>
              </div>

              <div class="field">
                <%= form.label :category %>
                <%= form.text_field :category, id: :book_category, class: 'form-control erase' %>
              </div>

              <div class="field">
                <%= form.label :price %>
                <%= form.text_field :price, id: :book_price, class: 'form-control erase' %>
              </div>

              <div class="field">
                <%= form.label :isbn %>
                <%= form.number_field :isbn, id: :book_isbn, class: 'form-control erase' %>
              </div>

            
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                  <%= submit_tag :Save, class: "btn btn-primary" %>
                </div>
  
    </div>
  </div>
</div>
</div>
    <% end %>

  

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Category:</strong>
  <%= @book.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @book.price %>
</p>

<p>
  <strong>Isbn:</strong>
  <%= @book.isbn %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="<%= root_path %>">RoR</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="<%= root_path %>">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <%= link_to 'Advance Search', new_search_path, class: 'nav-link' %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Login
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
          <div class="dropdown-divider"></div>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
     
    </ul>
    <%= form_tag books_path, method: 'GET', class: "form-inline my-2 my-lg-0" do %>
      <%= text_field_tag :search, params[:search], class: "form-control mr-sm-2", placeholder: "Search" %>
      <%= submit_tag 'Search', name: nil, class: "btn btn-outline-success my-2 my-sm-0" %>
    <% end %>
  
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    

  </head>

  <body>
    <%= render 'layouts/header' %>

 
  <p class="alert"></p>

  	<div class="container">
    <%= yield %>
    </div>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
  </body>
</html>

app/views/searches/new.html.erb
<br><br><br><br><br><br>
<%= form_for @search do |f| %>
  
  <div class="row">
   
    <div class="col-md-6 mb-3">    
	    <%= f.label :keywords %>
		<%= f.text_field :keywords, class: 'form-control is-valid', placeholder: "Keyword", value: "Mark" %>
    </div>

    <div class="col-md-6 mb-3">
    	
    <%= f.label :category %>

	<%= f.text_field :category, class: 'form-control coti'  %>
    </div>

  </div>

  <div class="row">
    <div class="col-md-6 mb-3">
    	<%= f.label :min_price %>
		<%= f.text_field :min_price, size: 10, class: 'form-control is-valid', placeholder: "Min Price", value: "Mark" %>
     
    </div>
    <div class="col-md-3 mb-3">
      <%= f.label :max_price %>
	  <%= f.text_field :max_price, size: 10, class: 'form-control is-valid', placeholder: "Max Price", value: "Mark" %>
      
    </div>
    <div class="col-md-3 mb-3">
      <%= f.label :isbn %>
	  <%= f.text_field :isbn, size: 10, class: 'form-control is-valid', placeholder: "ISBN", value: "Mark" %>
    </div>

  </div>

	
	<%= f.submit 'Search', class: 'btn btn-primary' %> <%= link_to 'Back', books_path, class: 'btn btn-primary', style: 'color: white' %>
	
<div class="ui-widget">
  <label for="tags">Tags: </label>
  <input id="tags">
</div>

<% end %>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.11.4/jquery-ui.min.js"></script>
<script >

$(document).ready( function() {
    var availableTags = [
      "ActionScript",
      "AppleScript",
      "Asp",
      "BASIC",
      "C",
      "C++",
      "Clojure",
      "COBOL",
      "ColdFusion",
      "Erlang",
      "Fortran",
      "Groovy",
      "Haskell",
      "Java",
      "JavaScript",
      "Lisp",
      "Perl",
      "PHP",
      "Python",
      "Ruby",
      "Scala",
      "Scheme"
    ];
    $( "#tags" ).autocomplete({
      source: availableTags
    });
  } );
</script>

app/views/searches/show.html.erb
<div class= "row">


<% if @search.search_books.empty? %>

		<p> no record </p>
<% else %>

<% @search.search_books.each do |c| %>	
<div class='col-md-3 text-center box blog-main' id="book_id_<%= c.id %>" >
  	<div class="card" style="width: 270px; margin-bottom: 20px;" >
			 
			  <div class="card-body text-white bg-danger mb-3" >
			    <h4 class="card-title "><%= c.name %></h4>
			 </div>

				  <ul class="list-group list-group-flush">
				    <li class="list-group-item"><b>Category: </b><%= c.category %></li>
				    <li class="list-group-item"><b>Price: </b><%= c.price %></li>
				    <li class="list-group-item"><b>ISBN: </b><%= c.isbn %></li>
				  </ul>

		  <div class="card-body" >
		  	<div class="btn-group" role="group" aria-label="Basic example">
			    <%= link_to 'Show', c, class: 'card-link btn btn-primary',style: "color: black; background-color: white;" %>
			  	<%= link_to 'Edit', edit_book_path(c), class: 'card-link btn btn-info',style: "color: black; background-color: white;" %>
			    <%= link_to 'Destroy', c, method: :delete, remote: true, class: 'card-link btn btn-danger',style: "color: black; background-color: white;" %>
			</div>
		  </div>
	</div>
</div>
<% end %>
	
<% end %>
</div>
<br>
<p><%= link_to 'Back', new_search_path, class: 'btn btn-primary' %></p>